openssl_certificate:
  - path: "/etc/ssl/certs/grafana/grafana.crt"
    privatekey_path: "/etc/ssl/certs/grafana/private/grafana.pem"
    csr_path: "/etc/ssl/certs/grafana/grafana.csr"
    provider: "selfsigned"

# APACHE #
apache_listen_ip: "*"
apache_listen_port: 80
apache_listen_port_ssl: 443
apache_create_vhosts: true
apache_vhosts_filename: "vhosts.conf"
apache_vhosts_template: "vhosts.conf.j2"

apache_global_vhost_settings: |
  DirectoryIndex index.php index.html

apache_allow_override: "All"
apache_options: "-Indexes +FollowSymLinks"

apache_vhosts_ssl:
  - servername: "localhost"
    serveralias: "www.localhost"
    certificate_file: "/etc/ssl/certs/grafana/grafana.crt"
    certificate_key_file: "/etc/ssl/certs/grafana/private/grafana.key"
    documentroot: "/var/www/html/grafana"
    extra_parameters:
      - SSLProxyEngine on
