---

# APACHE #

apache_mods_enabled:
  - rewrite.load
  - ssl.load
  - proxy.load
  - proxy_http.load
  - xml2enc.load


# MySQL #

mysql_databases:
  - name: graphite
    collation: utf8_general_ci
    encoding: utf8

  - name: grafana
    collation: utf8_general_ci
    encoding: utf8

mysql_users:
  - name: graphite
    host: "localhost"
    password: graphite
    priv: '*.*:ALL,GRANT'

  - name: grafana
    host: "localhost"
    password: grafana
    priv: '*.*:ALL,GRANT'

mysql_user_name: root
mysql_user_password: vagrant
mysql_root_username: root
mysql_root_password: vagrant
mysql_root_password_update: yes
mysql_user_password_update: yes


# COLLECTD #

collectd_fdqnlookup: true
collectd_auto_load_plugin: true
collectd_write_graphite: yes
collectd_plugins: [disk, users]
collectd_default_plugins_options:
  disk:
  - Disk "/dev/mapper/vagrant--vg-root"
  - IgnoreSelected false
  cpu:
  - ReportByState = true
  - ReportByCpu = true
  - ValuesPercentage = false
  df:
  - ValuesPercentage True

# GRAFANA #

grafana_url: http://0.0.0.0:3000/grafana

grafana_server:
  protocol: http
  grafana_url: http://localhost:3000/grafana
  serve_from_sub_path: True

grafana_provisioning_synced: true

grafana_security:
  admin_user: admin
  admin_password: grafana
  secret_key: Super_secretKey_forGrafana

grafana_database:
  type: mysql
  host: localhost
  name: grafana
  user: graphite
  password: graphite

grafana_dashboards_dir: /var/lib/grafana/dashboards/

grafana_auth:
  disable_login_form: false
  anonymous:
    org_name: "Main Org."
    org_role: Editor

grafana_metrics:
 interval_seconds: 30
 graphite:
   address: "localhost:8080"
   prefix: "prod.grafana.%(instance_name)s"

grafana_datasources:
 - name: "graphite"
   type: "graphite"
   access: "proxy"
   url: "http://127.0.0.1:8080/"
   basicAuth: false
   isDefault: true
   editable: true
