---

dependencies: []

galaxy_info:
  author: klen
  company: Stouts
  description: Ansible role to install and setup Collectd
  license: MIT
  platforms:
  - name: Ubuntu
    versions:
    - all
  categories:
  - system
  - monitoring
